- hosts: localhost
  become: true

  vars:
    username: "ubuntu"
    userhome: "/home/{{ username }}"

  tasks:
  - include: tasks/configure-software-ubuntu.yaml
    when: ansible_facts["os_family"] == "Debian"
  - include: tasks/configure-user.yaml
