- name: Package Installation - Update Apt package cache
  apt:
    update_cache: true
  changed_when: false

- name: Package Installation - Productivity Tools
  package:
    name: [
        'gnome-terminal',
        'lynx'
    ]
    state: present
